import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
  alternates: {
    canonical: "https://yourdomain.com/blog",
  }  
};

async function getPosts() {
  const res = await fetch("https://jsonplaceholder.typicode.com/posts", {
    cache: "no-store",
  });

  return res.json();
}

export default async function BlogPage() {
  const posts = await getPosts();

  return (
    <div className="pageWrapper">
      <section className="pt-24 min-h-[300px] flex items-center bg-gray-100">
          <div className="max-w-7xl mx-auto px-4 text-center">
            <h1 className="text-5xl font-bold">Blog</h1>
          </div>
        </section>
      <section className="py-10">
        <div className="max-w-5xl mx-auto px-4">


          <div className="grid gap-6">
            {posts.slice(0, 10).map((post: any) => (
              <a
                key={post.id}
                href={`/blog/${post.id}`}
                className="block p-4 border rounded-lg hover:shadow"
              >
                <h2 className="text-xl font-semibold mb-2">
                  {post.title}
                </h2>
                <p className="text-gray-600">
                  {post.body.substring(0, 100)}...
                </p>
              </a>
            ))}
          </div>

        </div>
      </section>
    </div>
  );
}