import type { Metadata } from "next";
import HeroVideo from "../components/HeroVideo";

export const metadata: Metadata = {
  title: "Integrations",
  description: "Generated by create next app",
  alternates: {
    canonical: "https://yourdomain.com/integrations",
  },
  openGraph: {
    title: "Integrations",
    description: "Explore our integrations",
    url: "https://yourdomain.com/integrations",
    siteName: "SendGrow",
    images: [
      {
        url: "https://yourdomain.com/assets/images/og-image.jpg",
        width: 1200,
        height: 630,
      },
    ],
    type: "website",
  },
};

export default function Home() {
  return (
    <div className="pageWrapper">
      <HeroVideo
          videoSrc="/assets/images/hero1.mp4"
          title="Integrations"
          subtitle="Automate and grow faster"
          buttonText="Book a Demo"
      />
      <section className="pt-24 min-h-[300px] flex items-center bg-gray-100">
        <div className="max-w-7xl mx-auto px-4 text-center">
          <h1 className="text-5xl font-bold">Integrations</h1>
          <p className="text-gray-600 mt-2">Explore</p>
        </div>
      </section>
      <section className="py-24">
        <div className="max-w-7xl mx-auto px-4">
          <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Unde dolores officiis corrupti corporis cumque fugiat dicta praesentium vitae nostrum, ducimus facilis pariatur porro veniam provident quia quaerat, in quo. Minus!
          Repellendus quibusdam nulla voluptatibus error esse molestiae aperiam aliquid sapiente voluptatum alias iure voluptas quia earum nesciunt ratione facilis ipsa hic tempore sunt doloribus, minus ipsam! Itaque quisquam quia et.
          Iste et culpa facilis, facere iure officiis omnis excepturi corporis incidunt est molestias numquam deserunt accusantium delectus eius maiores rerum non ratione placeat? Cum eius explicabo enim quaerat accusamus id.</p>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-3 mb-4">
            <div className="border flex">
                <div className="bg-white shadow-lg hover:shadow-xl transition flex flex-col w-full">

                  <div className="border-b px-5 py-4">
                    <h3 className="text-xl font-bold text-gray-800 line-clamp-1">Header</h3>
                  </div>

                  <div className="px-5 py-4 flex-1">
                    <img className="h-40 w-full rounded-xl mb-4 object-cover" src="./assets/images/screen1.jpg" alt="" />
                    <p className="text-gray-600 leading-relaxed">
                      Lorem, ipsum dolor sit amet consectetur adipisicing elit.
                    </p>
                  </div>

                  <div className="border-t px-5 py-4 text-sm text-gray-500 mt-auto">
                    Footer
                  </div>

                </div>              
            </div>
            <div className="border flex">
                <div className="bg-white shadow-lg hover:shadow-xl transition flex flex-col w-full">

                  <div className="border-b px-5 py-4">
                    <h3 className="text-xl font-bold text-gray-800 line-clamp-1">dolor sit amet consectetur adipisicing elit</h3>
                  </div>

                  <div className="px-5 py-4 flex-1">
                    <p className="text-gray-600 leading-relaxed">
                      Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quae voluptate quas in! Omnis voluptate itaque culpa? Sunt repellendus dolore, necessitatibus obcaecati maxime facere ex alias incidunt minima possimus quo ratione.
                    </p>
                  </div>

                  <div className="border-t px-5 py-4 text-sm text-gray-500 mt-auto">
                    Footer
                  </div>

                </div>

            </div>
            <div className="border flex justify-center items-center">3</div>
            <div className="border flex justify-center items-center">4</div>
          </div>

          <p>Accusantium, eveniet delectus. Expedita eos fuga corporis mollitia at culpa voluptatibus quis iure, quibusdam sequi laborum eum! Veniam quidem assumenda ratione consectetur quod nemo consequuntur molestias corporis, culpa accusamus sed? Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi eos error iste voluptatem iusto? Culpa veritatis quia nostrum iusto consectetur natus consequuntur, ullam eius dignissimos accusamus nemo, nisi est alias?</p>
        
          <div
            className="relative mx-auto -my-px h-80 max-w-md overflow-auto bg-white shadow-lg ring-1 ring-gray-900/5 dark:bg-gray-800">
            <div className="relative">
                <div
                    className="sticky top-0 flex items-center bg-gray-50/90 px-4 py-3 text-sm font-semibold text-gray-900 ring-1 ring-gray-900/10 backdrop-blur-sm dark:bg-gray-700/90 dark:text-gray-200 dark:ring-black/10">
                    A</div>
                <div className="divide-y divide-gray-200 dark:divide-gray-200/5">
                    <div className="flex items-center gap-4 p-4"><img className="size-12 rounded-full"
                            src="https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=facearea&amp;facepad=4&amp;w=256&amp;h=256&amp;q=80" /><strong
                            className="text-sm font-medium text-gray-900 dark:text-gray-200">Andrew Alfred</strong></div>
                    <div className="flex items-center gap-4 p-4"><img className="size-12 rounded-full"
                            src="https://images.unsplash.com/photo-1531123897727-8f129e1688ce?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=facearea&amp;facepad=4&amp;w=256&amp;h=256&amp;q=80" /><strong
                            className="text-sm font-medium text-gray-900 dark:text-gray-200">Aisha Houston</strong></div>
                    <div className="flex items-center gap-4 p-4"><img className="size-12 rounded-full"
                            src="https://images.unsplash.com/photo-1517841905240-472988babdf9?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=facearea&amp;facepad=4&amp;w=256&amp;h=256&amp;q=80" /><strong
                            className="text-sm font-medium text-gray-900 dark:text-gray-200">Anna White</strong></div>
                    <div className="flex items-center gap-4 p-4"><img className="size-12 rounded-full"
                            src="https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=facearea&amp;facepad=4&amp;w=256&amp;h=256&amp;q=80" /><strong
                            className="text-sm font-medium text-gray-900 dark:text-gray-200">Andy Flint</strong></div>
                </div>
            </div>
            <div className="relative">
                <div
                    className="sticky top-0 flex items-center bg-gray-50/90 px-4 py-3 text-sm font-semibold text-gray-900 ring-1 ring-gray-900/10 backdrop-blur-sm dark:bg-gray-700/90 dark:text-gray-200 dark:ring-black/10">
                    B</div>
                <div className="divide-y divide-gray-200 dark:divide-gray-200/5">
                    <div className="flex items-center gap-4 p-4"><img className="size-12 rounded-full"
                            src="https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=facearea&amp;facepad=4&amp;w=256&amp;h=256&amp;q=80" /><strong
                            className="text-sm font-medium text-gray-900 dark:text-gray-200">Bob Alfred</strong></div>
                    <div className="flex items-center gap-4 p-4"><img className="size-12 rounded-full"
                            src="https://images.unsplash.com/photo-1531123897727-8f129e1688ce?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=facearea&amp;facepad=4&amp;w=256&amp;h=256&amp;q=80" /><strong
                            className="text-sm font-medium text-gray-900 dark:text-gray-200">Bianca Houston</strong></div>
                    <div className="flex items-center gap-4 p-4"><img className="size-12 rounded-full"
                            src="https://images.unsplash.com/photo-1517841905240-472988babdf9?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=facearea&amp;facepad=4&amp;w=256&amp;h=256&amp;q=80" /><strong
                            className="text-sm font-medium text-gray-900 dark:text-gray-200">Brianna White</strong></div>
                    <div className="flex items-center gap-4 p-4"><img className="size-12 rounded-full"
                            src="https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=facearea&amp;facepad=4&amp;w=256&amp;h=256&amp;q=80" /><strong
                            className="text-sm font-medium text-gray-900 dark:text-gray-200">Bert Flint</strong></div>
                </div>
            </div>

            <div className="relative">
                <div
                    className="sticky top-0 flex items-center bg-gray-50/90 px-4 py-3 text-sm font-semibold text-gray-900 ring-1 ring-gray-900/10 backdrop-blur-sm dark:bg-gray-700/90 dark:text-gray-200 dark:ring-black/10">
                    C</div>
                <div className="divide-y divide-gray-200 dark:divide-gray-200/5">
                    <div className="flex items-center gap-4 p-4"><img className="size-12 rounded-full"
                            src="https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=facearea&amp;facepad=4&amp;w=256&amp;h=256&amp;q=80" /><strong
                            className="text-sm font-medium text-gray-900 dark:text-gray-200">Colton Alfred</strong></div>
                    <div className="flex items-center gap-4 p-4"><img className="size-12 rounded-full"
                            src="https://images.unsplash.com/photo-1531123897727-8f129e1688ce?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=facearea&amp;facepad=4&amp;w=256&amp;h=256&amp;q=80" /><strong
                            className="text-sm font-medium text-gray-900 dark:text-gray-200">Cynthia Houston</strong></div>
                    <div className="flex items-center gap-4 p-4"><img className="size-12 rounded-full"
                            src="https://images.unsplash.com/photo-1517841905240-472988babdf9?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=facearea&amp;facepad=4&amp;w=256&amp;h=256&amp;q=80" /><strong
                            className="text-sm font-medium text-gray-900 dark:text-gray-200">Cheyenne White</strong></div>
                    <div className="flex items-center gap-4 p-4"><img className="size-12 rounded-full"
                            src="https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?ixlib=rb-1.2.1&amp;ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&amp;auto=format&amp;fit=facearea&amp;facepad=4&amp;w=256&amp;h=256&amp;q=80" /><strong
                            className="text-sm font-medium text-gray-900 dark:text-gray-200">Charlie Flint</strong></div>
                </div>
            </div>


        </div>



        <div className="pt-20">
            <figure className="flex flex-col gap-1 rounded-xl bg-gray-950/5 p-1 inset-ring inset-ring-gray-950/5 dark:bg-white/10 dark:inset-ring-white/10">
              <div className="not-prose overflow-auto rounded-lg bg-white outline outline-white/5 dark:bg-gray-950/50 ">
                <div className="overflow-x-auto">
                    <table className="w-full table-auto border-collapse text-sm md:table-fixed">                      
                        <tbody>
                            <tr className="ff-heading">
                                <th>&nbsp;</th>
                                <th className="text-center">Quarter</th>
                                <th className="text-center">Since Inception</th>
                                <th className="text-center">1 Year</th>
                                <th className="text-center">3 Year</th>
                                <th className="text-center">5 Year</th>
                                <th className="text-center">Since Inception</th>
                            </tr>
                            <tr>
                                <th className="firstTd">Fund NAV</th>
                                <td className="text-center">0.00%</td>
                                <td className="text-center">0.00%</td>
                                <td className="text-center">0.00%</td>
                                <td className="text-center">0.00%</td>
                                <td className="text-center">0.00%</td>
                                <td className="text-center">0.00%</td>
                            </tr> 
                            <tr>
                                <th className="firstTd">Market Price</th>
                                <td className="text-center">0.00%</td>
                                <td className="text-center">0.00%</td>
                                <td className="text-center">0.00%</td>
                                <td className="text-center">0.00%</td>
                                <td className="text-center">0.00%</td>
                                <td className="text-center">0.00%</td>
                            </tr>
                            <tr>
                                <th className="firstTd">Benchmark <span className="fs-13 fw-normal">optional</span></th>
                                <td className="text-center">0.00%</td>
                                <td className="text-center">0.00%</td>
                                <td className="text-center">0.00%</td>
                                <td className="text-center">0.00%</td>
                                <td className="text-center">0.00%</td>
                                <td className="text-center">0.00%</td>
                            </tr>                              
                        </tbody>
                    </table>                
                </div>
              </div>
            </figure>
        </div>
        
        
        </div>
        
      </section>
    </div>
  );
}