import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import FancyboxProvider from "./components/FancyboxProvider";
import Header from "./components/Header";
import Footer from "./components/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap", // 🔥 important for performance
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* ✅ yaha apply karo */}
      <body className={`${poppins.className} min-h-full flex flex-col`}>
        <FancyboxProvider />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}