import type { Metadata } from "next";
import Accordion from "../components/Accordion";

export const metadata: Metadata = {
  title: "Plans",
  description: "Generated by create next app",
  alternates: {
    canonical: "https://yourdomain.com/plans",
  },
  openGraph: {
    title: "Plans",
    description: "Explore our plans",
    url: "https://yourdomain.com/plans",
    siteName: "SendGrow",
    images: [
      {
        url: "https://yourdomain.com/assets/images/og-image.jpg",
        width: 1200,
        height: 630,
      },
    ],
    type: "website",
  },
};


export default function Plans() {
  const data = [
    {
      title: "Are there any discounts?",
      content: "Yes! You’ll get early bird offers and bundle deals.",
    },
    {
      title: "Event dates?",
      content: "From Sept 10 to Sept 15 in multiple cities.",
    },
    {
      title: "Can I bring a guest?",
      content: "Yes, 1 guest allowed per attendee.",
    },
  ];
  return (
    <div className="pageWrapper">
      
      <section className="pt-24 min-h-[300px] flex items-center bg-gray-100">
        <div className="max-w-7xl mx-auto px-4 text-center">
          <h1 className="text-5xl font-bold">Plans</h1>
          <p className="text-gray-600 mt-2">Explore our plans</p>
        </div>
      </section>

      <section className="pb-15">
        <div className="max-w-7xl mx-auto px-4 text-center">
            <div className="px-4 py-8">
      <div className="max-w-4xl mx-auto">
        <div className="text-center">
          <h2 className="text-slate-900 text-3xl md:text-4xl font-bold mb-4">Choose the right plan for you</h2>
          <p className="text-[15px] text-slate-600">Flexible plans designed for individuals, teams, and growing businesses.</p>
        </div>

        <div className="grid md:grid-cols-2 items-center gap-y-6 mt-12 max-md:max-w-md max-md:mx-auto">
          <div className="bg-white border border-gray-300 shadow-sm md:rounded-tl-3xl md:rounded-bl-3xl max-md:rounded-3xl p-8 sm:p-10">
            <div>
              <h3 className="text-slate-900 text-4xl font-semibold">$10 <sub className="text-slate-600 text-[15px] font-normal">/ per month</sub></h3>
            </div>

            <div className="mt-8">
              <h4 className="text-slate-900 text-lg font-semibold">Individual Plan</h4>

              <ul className="mt-6 space-y-5">
                <li className="flex items-center text-[15px] text-slate-600 font-medium">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" className="mr-3 fill-green-500" viewBox="0 0 24 24">
                    <path d="M9.707 19.121a.997.997 0 0 1-1.414 0l-5.646-5.647a1.5 1.5 0 0 1 0-2.121l.707-.707a1.5 1.5 0 0 1 2.121 0L9 14.171l9.525-9.525a1.5 1.5 0 0 1 2.121 0l.707.707a1.5 1.5 0 0 1 0 2.121z" data-original="#000000" />
                  </svg>
                  50 Page Unlock
                </li>
                <li className="flex items-center text-[15px] text-slate-600 font-medium">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" className="mr-3 fill-green-500" viewBox="0 0 24 24">
                    <path d="M9.707 19.121a.997.997 0 0 1-1.414 0l-5.646-5.647a1.5 1.5 0 0 1 0-2.121l.707-.707a1.5 1.5 0 0 1 2.121 0L9 14.171l9.525-9.525a1.5 1.5 0 0 1 2.121 0l.707.707a1.5 1.5 0 0 1 0 2.121z" data-original="#000000" />
                  </svg>
                  10 GB Storage
                </li>
                <li className="flex items-center text-[15px] text-slate-600 font-medium">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" className="mr-3 fill-green-500" viewBox="0 0 24 24">
                    <path d="M9.707 19.121a.997.997 0 0 1-1.414 0l-5.646-5.647a1.5 1.5 0 0 1 0-2.121l.707-.707a1.5 1.5 0 0 1 2.121 0L9 14.171l9.525-9.525a1.5 1.5 0 0 1 2.121 0l.707.707a1.5 1.5 0 0 1 0 2.121z" data-original="#000000" />
                  </svg>
                  6 Team Members
                </li>
                <li className="flex items-center text-[15px] text-slate-600 font-medium">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" className="mr-3 fill-green-500" viewBox="0 0 24 24">
                    <path d="M9.707 19.121a.997.997 0 0 1-1.414 0l-5.646-5.647a1.5 1.5 0 0 1 0-2.121l.707-.707a1.5 1.5 0 0 1 2.121 0L9 14.171l9.525-9.525a1.5 1.5 0 0 1 2.121 0l.707.707a1.5 1.5 0 0 1 0 2.121z" data-original="#000000" />
                  </svg>
                  Priority Email Support
                </li>
                <li className="flex items-center text-[15px] text-slate-600 font-medium">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" className="mr-3 fill-green-500" viewBox="0 0 24 24">
                    <path d="M9.707 19.121a.997.997 0 0 1-1.414 0l-5.646-5.647a1.5 1.5 0 0 1 0-2.121l.707-.707a1.5 1.5 0 0 1 2.121 0L9 14.171l9.525-9.525a1.5 1.5 0 0 1 2.121 0l.707.707a1.5 1.5 0 0 1 0 2.121z" data-original="#000000" />
                  </svg>
                  Access on all devices
                </li>
                <li className="flex items-center text-[15px] text-slate-600 font-medium">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" className="mr-3 fill-green-500" viewBox="0 0 24 24">
                    <path d="M9.707 19.121a.997.997 0 0 1-1.414 0l-5.646-5.647a1.5 1.5 0 0 1 0-2.121l.707-.707a1.5 1.5 0 0 1 2.121 0L9 14.171l9.525-9.525a1.5 1.5 0 0 1 2.121 0l.707.707a1.5 1.5 0 0 1 0 2.121z" data-original="#000000" />
                  </svg>
                  Export to PDF
                </li>
              </ul>

              <button type="button" className="w-full mt-8 px-4 py-2.5 text-[15px] font-medium text-white bg-indigo-600 hover:bg-indigo-700 rounded-md cursor-pointer">Buy Plan</button>
            </div>
          </div>

          <div className="bg-slate-900 border border-gray-900 shadow-2xl rounded-3xl p-8 sm:p-10 relative md:right-1">
            <div>
              <h3 className="text-white text-4xl font-semibold">$20 <sub className="text-slate-300 text-[15px] font-normal">/ per month</sub></h3>
            </div>

            <div className="mt-8">
              <h4 className="text-white text-lg font-semibold">Business Plan</h4>

              <ul className="mt-6 space-y-5">
                <li className="flex items-center text-[15px] text-slate-300 font-medium">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" className="mr-3 fill-green-500" viewBox="0 0 24 24">
                    <path d="M9.707 19.121a.997.997 0 0 1-1.414 0l-5.646-5.647a1.5 1.5 0 0 1 0-2.121l.707-.707a1.5 1.5 0 0 1 2.121 0L9 14.171l9.525-9.525a1.5 1.5 0 0 1 2.121 0l.707.707a1.5 1.5 0 0 1 0 2.121z" data-original="#000000" />
                  </svg>
                  100 Page Unlock
                </li>
                <li className="flex items-center text-[15px] text-slate-300 font-medium">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" className="mr-3 fill-green-500" viewBox="0 0 24 24">
                    <path d="M9.707 19.121a.997.997 0 0 1-1.414 0l-5.646-5.647a1.5 1.5 0 0 1 0-2.121l.707-.707a1.5 1.5 0 0 1 2.121 0L9 14.171l9.525-9.525a1.5 1.5 0 0 1 2.121 0l.707.707a1.5 1.5 0 0 1 0 2.121z" data-original="#000000" />
                  </svg>
                  20 GB Storage
                </li>
                <li className="flex items-center text-[15px] text-slate-300 font-medium">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" className="mr-3 fill-green-500" viewBox="0 0 24 24">
                    <path d="M9.707 19.121a.997.997 0 0 1-1.414 0l-5.646-5.647a1.5 1.5 0 0 1 0-2.121l.707-.707a1.5 1.5 0 0 1 2.121 0L9 14.171l9.525-9.525a1.5 1.5 0 0 1 2.121 0l.707.707a1.5 1.5 0 0 1 0 2.121z" data-original="#000000" />
                  </svg>
                  10 Team Members
                </li>
                <li className="flex items-center text-[15px] text-slate-300 font-medium">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" className="mr-3 fill-green-500" viewBox="0 0 24 24">
                    <path d="M9.707 19.121a.997.997 0 0 1-1.414 0l-5.646-5.647a1.5 1.5 0 0 1 0-2.121l.707-.707a1.5 1.5 0 0 1 2.121 0L9 14.171l9.525-9.525a1.5 1.5 0 0 1 2.121 0l.707.707a1.5 1.5 0 0 1 0 2.121z" data-original="#000000" />
                  </svg>
                  Unlimited Book Mark
                </li>
                <li className="flex items-center text-[15px] text-slate-300 font-medium">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" className="mr-3 fill-green-500" viewBox="0 0 24 24">
                    <path d="M9.707 19.121a.997.997 0 0 1-1.414 0l-5.646-5.647a1.5 1.5 0 0 1 0-2.121l.707-.707a1.5 1.5 0 0 1 2.121 0L9 14.171l9.525-9.525a1.5 1.5 0 0 1 2.121 0l.707.707a1.5 1.5 0 0 1 0 2.121z" data-original="#000000" />
                  </svg>
                  Unlimited basic feature
                </li>
                <li className="flex items-center text-[15px] text-slate-300 font-medium">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" className="mr-3 fill-green-500" viewBox="0 0 24 24">
                    <path d="M9.707 19.121a.997.997 0 0 1-1.414 0l-5.646-5.647a1.5 1.5 0 0 1 0-2.121l.707-.707a1.5 1.5 0 0 1 2.121 0L9 14.171l9.525-9.525a1.5 1.5 0 0 1 2.121 0l.707.707a1.5 1.5 0 0 1 0 2.121z" data-original="#000000" />
                  </svg>
                  Priority Chat + Email Support
                </li>
                <li className="flex items-center text-[15px] text-slate-300 font-medium">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" className="mr-3 fill-green-500" viewBox="0 0 24 24">
                    <path d="M9.707 19.121a.997.997 0 0 1-1.414 0l-5.646-5.647a1.5 1.5 0 0 1 0-2.121l.707-.707a1.5 1.5 0 0 1 2.121 0L9 14.171l9.525-9.525a1.5 1.5 0 0 1 2.121 0l.707.707a1.5 1.5 0 0 1 0 2.121z" data-original="#000000" />
                  </svg>
                  Advanced Analytics Dashboard
                </li>
                <li className="flex items-center text-[15px] text-slate-300 font-medium">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" className="mr-3 fill-green-500" viewBox="0 0 24 24">
                    <path d="M9.707 19.121a.997.997 0 0 1-1.414 0l-5.646-5.647a1.5 1.5 0 0 1 0-2.121l.707-.707a1.5 1.5 0 0 1 2.121 0L9 14.171l9.525-9.525a1.5 1.5 0 0 1 2.121 0l.707.707a1.5 1.5 0 0 1 0 2.121z" data-original="#000000" />
                  </svg>
                  Team Roles & Permissions
                </li>
              </ul>

              <button type="button" className="w-full mt-8 px-4 py-2.5 text-[15px] font-medium text-white bg-indigo-600 hover:bg-indigo-700 rounded-md cursor-pointer">Buy Plan</button>
            </div>
          </div>
        </div>
      </div>
    </div>  



      <div className="mt-15">
        <Accordion items={data} /> 
      </div>


    
          
            
        </div>
      </section>
    </div>
  );
}