import type { Metadata } from "next";
import ProductList from "../components/ProductList";
import ProductSlider from "../components/ProductSlider";
export const metadata: Metadata = {
  title: "Products",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="pageWrapper">
      <section className="pt-24 min-h-[300px] flex items-center bg-gray-100">
        <div className="max-w-7xl mx-auto px-4 text-center">
          <h1 className="text-5xl font-bold">Products</h1>
          <p className="text-gray-600 mt-2">Explore our products</p>
        </div>
      </section>        
      <ProductList />
      <ProductSlider />
    </div>
  );
}